### ISSUE TITLE
[bug] Power 2 being applied to already power 2

### ISSUE THREAD

**Issue by RebeccaStevens** [oblivioncth/Stexatlaser#1] opened 2021-10-12 09:38 UTC
When giving stex a folder containing a single image that is already a power 2, stex outputs a tex file with the next level up of power 2 (i.e. an input image of dimensions 128x128 will result in an output tex of dimensions 256x256).

Additionally the atlas file has an off by 1px error with regard to the width of the element.
The resulting element's size for an input of 128x128 is 127x128.

- The `u2` value is `0.496094` (it should be `0.5`)
- The `v2` value of `0.996094` (it should be `1`) - though this seems to be close enough to 1 for the element to sill be read as the height being 128px)

**Comment by oblivioncth** [comment] 2021-10-12 18:47
Thanks for the submission.

This happens because the packing routine adds a 1px margin (as can be observed in the example) to all of the source images in order to help prevent texture overlap in edge cases where floating point inaccuracies or rounding would cause the game to be off-by-one in its pixel references when converting from the integer absolute coordinates to the decimal relative coordinates. The atlas key is still setup to reference the correct original size which is why you see slightly smaller than expected relative coordinates, as the extra margin pixel makes the original width go from half the image to ~49.6% of the image. Same for the height.

This is applied indiscriminately and so it does cause a bit of an unexpected output when using only 1 source image that happens to already have power of 2 dimensions. Since this was intended as an atalser for multiple images and not as a way to just convert one image, this isn't a case I had considered; however, there is no reason you shouldn't be able to use it that way, and I can see how a common situation might be that you're batch processing a bunch of atlases and a few of them happen to only contain one image. It would certainly be unreasonable to expect the user to make sure they set aside the source folders that happen to have one image and tell them to use other software to convert those specifically.

I will add in a check for this specific case and have it bypass the packing routine altogether, so that the image is converted to TEX as is, with an atlas as you'd expect.

**Comment by oblivioncth** [comment] 2021-10-14 04:46
Fixed by [48a9875](https://github.com/oblivioncth/Stexatlaser/commit/48a9875a60840887ac61f846ec90878ec681ddbd)

**Closed as completed by oblivioncth** 2021-10-14 04:46 UTC
Labels: bug
